/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_badata_tesstwoexample_camera_CameraView */

#ifndef _Included_net_badata_tesstwoexample_camera_CameraView
#define _Included_net_badata_tesstwoexample_camera_CameraView
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_net_badata_tesstwoexample_camera_CameraView_decode(JNIEnv *pEnv, jclass pClass, jobject pTarget, jbyteArray pSource);
#ifdef __cplusplus
}
#endif
#endif
